#!/usr/bin/env bash

# we'll receive lines like:
# /gut/scrapes/tumblr_by_blog/artimages.tumblr.com/ ACCESS aHR0cDovLzY1Lm1llslGlhLnR1bWJsci5jb20vZThYTNjYTY3NmY2NmRlNTAxMmIzMQZmEzNjMDgvdHVtYmxyX5jcx5b2pjZGwxcWx3Z2l5bzFfMTI4MC5qcGc=.jpg

host=$1
echo "connecting to mqtt server $host, waiting on updated jpgs"

mosquitto_sub -h $host -t '#' | grep "jpg$" | while read l; do
  dir=$(echo "$l" | cut -d' ' -f1)
  action=$(echo "$l" | cut -d' ' -f2)
  filename=$(echo "$l" | cut -d' ' -f3)
  filepath="$DATA_ROOT/$dir/$filename"
  outpath="$filepath.colors"
  if [[ "$action" == *"CLOSE_WRITE"* ]]; then
    echo "dumping colors: $filepath"
    dcolor -k 10 "$filepath" > "$outpath"
  fi
done

